version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  
      
  scheduler:
    build: .
    command: /bin/bash -c "airflow db init && airflow scheduler && airflow webserver && airflow users create --username airflow --firstname FIRST_NAME  --lastname LAST_NAME --role Admin --email admin@example.com "
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=mNyKhq7ErnV1PCicw4jYgW3KnbJ4awKb9hn2-U_gFKw=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/usr/local/airflow/logs  
      - ./:/opt/airflow/
    env_file:
      - ./.env

  webserver:
    build: .
    command: airflow db init && airflow webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5
   
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/usr/local/airflow/logs  

    env_file:
      - ./.env

volumes:
  airflow_logs:
