CREATE TABLE IF NOT EXISTS innk_dw_dev.public.dim_users (
    id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL UNIQUE,
    users VARCHAR(24000), 
    company_id INT,
    idea_db_id INT,
    user_db_id INT,
    user_name VARCHAR(2400),
    user_last_name VARCHAR(2400),
    user_email VARCHAR(2400),
    user_position VARCHAR(2400),
    user_contract_profile VARCHAR(2400),
    user_area VARCHAR(2400),
    user_sub_area VARCHAR(2400),
    user_country VARCHAR(2400),
    CONSTRAINT fk_id_company FOREIGN KEY (company_id) REFERENCES dim_company(id),
    created_at TIMESTAMP WITHOUT TIME ZONE   ENCODE az64,
    updated_at TIMESTAMP WITHOUT TIME ZONE   ENCODE az64,
    valid_from TIMESTAMP WITHOUT TIME ZONE   ENCODE az64,
    valid_to TIMESTAMP WITHOUT TIME ZONE   ENCODE az64,
    is_current BOOLEAN DEFAULT TRUE
)